services:
  haproxy:
    image: haproxy:alpine
    ports:
      - "9999:9999"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      api1:
        condition: service_healthy
      api2:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "30MB"
    networks:
      - rinha

  api1:
    image: ewertonlim/rinha-api:latest
    hostname: api1
    environment:
      - PORT=8080
      - INDEX_PATH=/data/index.bin
      - NORM_PATH=/data/normalization.json
      - MCC_PATH=/data/mcc_risk.json
      - NPROBE=10
    healthcheck:
      test: [ "CMD", "wget", "-q", "-O", "/dev/null", "http://127.0.0.1:8080/ready" ]
      interval: 2s
      timeout: 2s
      retries: 30
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "160MB"
    networks:
      - rinha

  api2:
    image: ewertonlim/rinha-api:latest
    hostname: api2
    environment:
      - PORT=8080
      - INDEX_PATH=/data/index.bin
      - NORM_PATH=/data/normalization.json
      - MCC_PATH=/data/mcc_risk.json
      - NPROBE=10
    healthcheck:
      test: [ "CMD", "wget", "-q", "-O", "/dev/null", "http://127.0.0.1:8080/ready" ]
      interval: 2s
      timeout: 2s
      retries: 30
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "160MB"
    networks:
      - rinha

networks:
  rinha:
    driver: bridge
